sudo: required # making use of docker
services:
  - docker
before_install:
  - openssl aes-256-cbc -K $encrypted_0c35eebf403c_key -iv $encrypted_0c35eebf403c_iv -in service-account.json.enc -out service-account.json -d #comes from travis encrypting service-account.json
  - curl https://sdk.cloud.google.com | bash > /dev/null; # Download and install google cloud SDK
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl # install and update kubectl in travis
  - gcloud auth activate-service-account --key-file service-account.json # Authorise glcoud using service-account.json
